"""Add detected_county_ids to voter_imports

Revision ID: 2c80b65c1cf1
Revises: 4de6f87c264e
Create Date: 2026-02-11 16:04:50.179812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c80b65c1cf1'
down_revision = '4de6f87c264e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voters_backup_1')
    op.drop_table('voters_backup_3')
    op.drop_table('voters_backup_2')
    with op.batch_alter_table('voter_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_county_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_imports', schema=None) as batch_op:
        batch_op.drop_column('detected_county_ids')

    op.create_table('voters_backup_2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sos_voterid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('county_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_address1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('residential_address2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('residential_zip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('precinct_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('precinct_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ward', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    op.create_table('voters_backup_3',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sos_voterid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('county_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_address1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('residential_address2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('residential_zip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('precinct_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('precinct_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ward', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    op.create_table('voters_backup_1',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sos_voterid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('county_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_address1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('residential_address2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('residential_zip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('precinct_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('precinct_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ward', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
