"""Add role field to users

Revision ID: 7b75052ca987
Revises: 
Create Date: 2026-02-10 10:27:44.306139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b75052ca987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, set default for existing rows, then make non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # Set existing users to 'admin' role (assuming first user is admin)
    op.execute("UPDATE users SET role = 'admin' WHERE role IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.create_index('idx_voters_address_btree', ['residential_address1'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_index('idx_voters_address_btree')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
