"""Rename county_id to county_number

Revision ID: e87ff0e61af2
Revises: 2c80b65c1cf1
Create Date: 2026-02-11 16:23:25.187825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87ff0e61af2'
down_revision = '2c80b65c1cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voters_backup_4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voters_backup_4',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sos_voterid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('county_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_address1', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('residential_address2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('residential_state', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('residential_zip', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('precinct_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('precinct_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ward', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
